name: Run Tests

on:
  pull_request:

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-slim
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.10.4"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      
      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: ".python-version"

      - name: uv sync
        run: uv sync --frozen --dev

      - name: Run tests
        run: |
          set -e
          uv run pytest -s tests --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=nuh_helper tests | tee pytest-coverage.txt
          test ${PIPESTATUS[0]} -eq 0

      - name: Pytest coverage comment
        # Forks do not have the necessary permission to add a comment.
        if: github.event.pull_request.head.repo.fork == false
        uses: MishaKav/pytest-coverage-comment@dd5b80bde6d16941f336518e92929e89069d8451
        with:
          pytest-coverage-path: pytest-coverage.txt
          junitxml-path: pytest.xml
  