name: 'Check PR title'

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-slim
    permissions:
      pull-requests: read
    steps:
      - name: 'Check PR title'
        uses: health-informatics-uon/workflows/.github/workflows/pr-title.yml@1.0.0
