name: Release
permissions:
  contents: write
  pull-requests: write
  issues: write


on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - release:
        uses: health-informatics-uon/workflows/.github/workflows/semantic-release.yml@main
        with:
          node-version: '24'
        secrets: inherit
